apiVersion: elasticsearch.k8s.elastic.co/v1 
kind: Elasticsearch 
metadata: 
  name: quickstart 
spec: 
  version: 8.3.3 #Make sure you use the version of your choice 
  # http: 
  #   service: 
  #     spec: 
  #       type: LoadBalancer #Adds a Internal IP 
  nodeSets: 
  - name: default 
    count: 1 
    config: 
      node.store.allow_mmap: false 